language: cpp

dist: bionic

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
    - BOOST=config-boost-1.73.0/include
  jobs:
    - CXXSTD=c++11

jobs:
  exclude:
    - os: osx
      compiler: gcc

install:
  - mkdir catch2
  - wget -O catch2/catch.hpp https://github.com/catchorg/Catch2/releases/download/v2.12.4/catch.hpp
  - wget https://github.com/boostorg/config/archive/boost-1.73.0.zip
  - unzip boost-1.73.0.zip

script:
  - echo ${BOOST}
  - make test
  - make run-test

notifications:
  email: false
