#ifndef BUFFER_HANDLE_MISC_HPP
#define BUFFER_HANDLE_MISC_HPP

#ifndef BUFFER_HANDLE_FALLTHROUGH

#ifdef BOOST_FALLTHROUGH

#define BUFFER_HANDLE_FALLTHROUGH BOOST_FALLTHROUGH

#else

#define BUFFER_HANDLE_FALLTHROUGH

#endif

#endif

#endif/*BUFFER_HANDLE_MISC_HPP*/
